# Generated by Django 3.1.2 on 2021-08-25 10:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('from_name', models.CharField(max_length=100)),
                ('to_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('passwords', models.CharField(max_length=100)),
                ('referral_code', models.CharField(default=api.models.pass_key, max_length=100)),
                ('incentives', models.IntegerField(default=0)),
            ],
        ),
    ]
